### PR TITLE
Pull request to allow driver to work with linux bridge

### PR DESCRIPTION
**Pull request by bkuschel**
Requires https://github.com/lxc/lxd/issues/1450 to be pulled. Veth name needs to be set in LXD so the linux bridge can pick up the tap device.

### CODE REVIEW

**Comment by zulcss** [comment]
Can you rebase this with the current branch please?

**Comment by bkuschel** [comment]
@zulcss I noticed that you removed  that wait for the vif plugged event. If there was a problem plugging the network the instance will come up as "Active" but there may be no network available (never or until some indeterminate time later until timeout). What were your thoughts around this?

**Comment by zulcss** [comment]
Hmm...yeah I have a PR branch that should be coming in today that addresses that.

**Comment by rockstar** [comment]
Hi @zulcss and @bkuschel - What's the status of this PR?

**Comment by rockstar** [comment]
We'll pick this patch back up when we address SDNs in the coming weeks.

**Pull request closed without merging**
